# ==========================================
#   Unity Project - A Test Framework for C
#   Copyright (c) 2007 Mike Karlesky, Mark VanderVoord, Greg Williams
#   [Released under MIT License. Please refer to license.txt for details]
# ========================================== 

CC = gcc
TARGET = build/test.out

UNITY_HOME = /home/agu/gitpool/Unity/src
# change UNITY_HOME to the local Unity path/src
# it coulde be generated by $ git clone https://github.com/ThrowTheSwitch/Unity.git

SRC_FILES = $(UNITY_HOME)/unity.c src/ProductionCode.c test/TestProductionCode.c test/TestProductionCode_Runner.c

INC_DIRS = -Isrc -I$(UNITY_HOME)
SYMBOLS = -DTEST

CLEANUP = rm -fr build/

all: clean default

default:
	mkdir -p build
	$(CC) $(INC_DIRS) $(SYMBOLS) $(SRC_FILES) -o $(TARGET)
	./$(TARGET)

clean:
	$(CLEANUP)
	
